### ISSUE TITLE
Changing colors - either does not work or being done improperly

### ISSUE THREAD

**Issue by kz** [Rawa/lifx_cli#1]
I'm looking to change the colors of my lights. However, I believe that either I'm doing something wrong, or something's broken. Here's my output:

```
➜  lifx-cli git:(master) ./lifx color -h360 -s1.0 -b1.0 -k9000
Bad color argument!
```

How would I approach changing lights properly?

**Comment by Rawa** [comment]
Hey, kz.

Sorry for the late reply didn't see this issue until now. I partially fixed the issue now and pushed it. However at the moment it is not possible to set a duration at the same time as selecting a color. I hope to fix this in the next couple of days, but i need to do some refactoring in the code to make it work properly.

Just simply run:
./lifx color -h 360 -s 1.0 -b 1.0 -k 9000
and it should work as intended (partially)

I will open a new issue regarding the duration not working when setting a color.
